-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;

DROP TABLE IF EXISTS catagory;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS productTag;

-- CREATE DATABASE
CREATE DATABASE ecommerce_db;

CREATE TABLE catagory (
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    category_name VARCHAR(30) NOT NULL
);
CREATE TABLE product (
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    product_name VARCHAR(30) NOT NULL,
    price DECIMAL(19, 4) NOT NULL,
    stock INTEGER NOT NULL,
    category_id INTEGER REFERENCES id (category) ON UPDATE RESTRICT ON DELETE CASCADE
);
CREATE TABLE tag (
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    tag_name VARCHAR(30)
);
CREATE TABLE productTag (
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    product_id INTEGER REFERENCES id (product) ON UPDATE RESTRICT ON DELETE CASCADE,
    tag_id INTEGER REFERENCES id (tag) ON UPDATE RESTRICT ON DELETE CASCADE
);